[versions]
springBoot = "3.5.7"
springDependencyManagement = "1.1.7"
flyway = "11.7.2"
jooqPlugin = "9.0"
jooq = "3.19.27"
postgresql = "42.7.8"
commonsLang3 = "3.17.0"
jacksonJsr310 = "2.19.2"

[libraries]
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-jooq = { group = "org.springframework.boot", name = "spring-boot-starter-jooq" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }
spring-tx = { group = "org.springframework", name = "spring-tx" }

flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }

postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }

commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jacksonJsr310" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
jooq = { id = "nu.studer.jooq", version.ref = "jooqPlugin" }
